### ISSUE TITLE
可以加上打开时密码校验

### ISSUE THREAD

**Issue by xxzj990** [baofengyv/Password-Book#3]
要不，任何人打开微信小程序都能随便看密码，加一个验证比较好。

**Comment by baofengyv** [comment]
首先，感谢您的关注。

这个问题我也考虑过。别人如果能打开你的微信，那他也能使用你的微信进行二维码付款了。
这样看来的话，密码的保密程度和二维码付款的保密程度是相同的。

我的一个重要原则是保持简洁。
